# Generated by Django 3.0.7 on 2020-06-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20200629_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_name_symbol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='companies_invested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='Customers.Stocks'),
        ),
    ]
