# Generated by Django 3.0.7 on 2020-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20200629_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Stock_name_symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
